server:
  port: 8082
spring:
  application:
    name: order-management-service

  datasource:
    url: jdbc:postgresql://localhost:5434/order_management
    username: myuser
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        logger-level: full
