version: '3'
services:
  postgres:
    image: postgres:14
    container_name: order-management-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_management
    ports:
      - "5434:5434" # Порт внутри и снаружи контейнера
    volumes:
      - C:\Users\user\Desktop\foodservice\postgres-data\order-management:/var/lib/postgresql/data
    command:
      - postgres
      - -p 5434 # Установка внутреннего порта PostgreSQL
