server:
  port: 8081

spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_management
    username: myuser
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 89184360274-njvh7vtc9n9u2n50n7994p3rred07106.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
      user:
        name-attributes: name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true